// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQrncP0I4RNX1DAuFS_PsljA2wzZsmY2U',
    appId: '1:718230008456:web:f36a8011de777cd0c7653d',
    messagingSenderId: '718230008456',
    projectId: 'homeharvest-d6d96',
    authDomain: 'homeharvest-d6d96.firebaseapp.com',
    storageBucket: 'homeharvest-d6d96.firebasestorage.app',
    measurementId: 'G-ZRPP16C125',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQrncP0I4RNX1DAuFS_PsljA2wzZsmY2U',
    appId: '1:718230008456:android:22e2b9354d3b2ca6c7653d',
    messagingSenderId: '718230008456',
    projectId: 'homeharvest-d6d96',
    authDomain: 'homeharvest-d6d96.firebaseapp.com',
    storageBucket: 'homeharvest-d6d96.firebasestorage.app',
    measurementId: 'G-VDEZBJFH4X',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQrncP0I4RNX1DAuFS_PsljA2wzZsmY2U',
    appId: '1:718230008456:ios:e8f36a8011de777cd0c7653d',
    messagingSenderId: '718230008456',
    projectId: 'homeharvest-d6d96',
    authDomain: 'homeharvest-d6d96.firebaseapp.com',
    storageBucket: 'homeharvest-d6d96.firebasestorage.app',
    iosBundleId: 'com.example.homeHarvestApp',
    measurementId: 'G-VDEZBJFH4X',
  );
}
